import { ref } from "vue";

export const animeNewAdded = ref([
  {
    title: "Jidou Hanbaiki ni Umarekawatta Ore wa...",
    name: "Reborn as a Vending Machine, I Now Wander the...",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "jidou-hanbaiki",
    view: "0",
  },
  {
    title: "Kanojo, Okarishimasu 4th Season",
    name: "Rent-a-Girlfriend Season 4",
    episode: 7,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "kanojo-okarishimasu-4",
    view: "0",
  },
  {
    title: "Meitantei Conan",
    name: "Thám Tử Lừng Danh Conan",
    episode: 1140,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "meitantei-conan",
    view: "0",
  },
  {
    title: "Mikadono Sanshimai wa Angai, Choroi.",
    name: "Đối Phó Với Chị Em Nhà Mikadono Thật Dễ Dàng",
    episode: 7,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "mikadono-sanshimai",
    view: "0",
  },
  {
    title: "Sakamoto Days Part 2",
    name: "SAKAMOTO DAYS Cour 2",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "sakamoto-days-part-2",
    view: "0",
  },
  {
    title: "Jidou Hanbaiki ni Umarekawatta Ore wa...",
    name: "Reborn as a Vending Machine, I Now Wander the...",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "jidou-hanbaiki",
    view: "0",
  },
  {
    title: "Kanojo, Okarishimasu 4th Season",
    name: "Rent-a-Girlfriend Season 4",
    episode: 7,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "kanojo-okarishimasu-4",
    view: "0",
  },
  {
    title: "Meitantei Conan",
    name: "Thám Tử Lừng Danh Conan",
    episode: 1140,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "meitantei-conan",
    view: "0",
  },
  {
    title: "Mikadono Sanshimai wa Angai, Choroi.",
    name: "Đối Phó Với Chị Em Nhà Mikadono Thật Dễ Dàng",
    episode: 7,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "mikadono-sanshimai",
    view: "0",
  },
  {
    title: "Sakamoto Days Part 2",
    name: "SAKAMOTO DAYS Cour 2",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "sakamoto-days-part-2",
    view: "0",
  },
  {
    title: "Jidou Hanbaiki ni Umarekawatta Ore wa...",
    name: "Reborn as a Vending Machine, I Now Wander the...",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "jidou-hanbaiki",
    view: "0",
  },
  {
    title: "Kanojo, Okarishimasu 4th Season",
    name: "Rent-a-Girlfriend Season 4",
    episode: 7,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "kanojo-okarishimasu-4",
    view: "0",
  },
  {
    title: "Meitantei Conan",
    name: "Thám Tử Lừng Danh Conan",
    episode: 1140,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "meitantei-conan",
    view: "0",
  },
  {
    title: "Mikadono Sanshimai wa Angai, Choroi.",
    name: "Đối Phó Với Chị Em Nhà Mikadono Thật Dễ Dàng",
    episode: 7,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "mikadono-sanshimai",
    view: "0",
  },
  {
    title: "Sakamoto Days Part 2",
    name: "SAKAMOTO DAYS Cour 2",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "sakamoto-days-part-2",
    view: "0",
  },
]);

export const animeRecentlyUpdated = ref([
  {
    title: "Grand Blue Season 2",
    name: "Cùng học bơi nào phần 2",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "grand-blue-season-2",
  },
  {
    title: "Clevatess: Majuu no Ou to Akago to...",
    name: "Clevatess",
    episode: 7,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "clevatess",
  },
  {
    title: "Jidou Hanbaiki ni Umarekawatta Ore wa...",
    name: "Reborn as a Vending Machine, I Now Wander the...",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "jidou-hanbaiki",
  },
  {
    title: "Kakkou no Iinazuke Season 2",
    name: "Cặp Đôi Tư HỮ Phần 2",
    episode: 6,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "kakkou-no-iinazuke-2",
  },
  {
    title: "Kanojo, Okarishimasu 4th Season",
    name: "Rent-a-Girlfriend Season 4",
    episode: 7,
    type: "TV",
    image: "/imgs/movie22.webp",
    slug: "kanojo-okarishimasu-4",
  },
]);

export const movieNew = ref([
  {
    title: "Dragon Ball Z Movie 08: Moetsukiro!! Nessen...",
    name: "Bảy Viên Ngọc Rồng Z Broly – Siêu Saiyan Huyền Thoại",
    episode: 1,
    type: "MOVIE",
    image: "/imgs/movie22.webp",
    slug: "dragon-ball-z-movie-08",
  },
  {
    title: "Meitantei Conan Movie 09: Suihei Senjou no...",
    name: "Thám Tử Lừng Danh Conan Movie 09: Âm Mưu Trên...",
    episode: 2,
    type: "MOVIE",
    image: "/imgs/movie22.webp",
    slug: "conan-movie-09",
  },
  {
    title: "Shingeki no Kyojin Movie: Kanketsu-hen –...",
    name: "Đại Chiến Người Khổng Lồ: Lần Tấn Công Cuối Cùng",
    episode: 1,
    type: "MOVIE",
    image: "/imgs/movie22.webp",
    slug: "aot-final-movie",
  },
  {
    title: "Shika no Ou: Yuna to Yakusoku no Tabi",
    name: "The Deer King",
    episode: 1,
    type: "MOVIE",
    image: "/imgs/movie22.webp",
    slug: "deer-king",
  },
  {
    title: "Na Tra 2",
    name: "Nezha: Mo tong nao hai",
    episode: 1,
    type: "MOVIE",
    image: "/imgs/movie22.webp",
    slug: "na-tra-2",
  },
]);
